name: Build & Push Docker image

on:
  push:
    branches: ["main", "master"]

jobs:
  docker-build:
    uses: ERP-CNAM/workflows-templates/.github/workflows/image-builder.yml@main
    with:
      context: .
      image-name: erp-cnam/gamers